image: node:16.10.0-alpine

stages:
    - deploy

prod:
    stage: deploy
    script:
        - npm install
        - npm run build-production
        - apk add --no-cache rsync sshpass openssh curl
        - mkdir -p ~/.ssh && chmod 777 ~/.ssh
        - sshpass -p $SSH_PASS_PROD rsync -riz --links -e "ssh -o StrictHostKeyChecking=no" $SSH_DIRECTORY_LOCAL_PROD $SSH_USER_PROD@$SSH_HOST_PROD:$SSH_DIRECTORY_REMOTE_PROD
    only:
        - main
        - dev
    environment:
        name: Production
